stages:
  load_data:
    cmd: /Users/B026289/anaconda3/bin/python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv